### ISSUE TITLE
Testing storybook components with focus pseudo class not working 

### ISSUE THREAD

**Issue by zalohcin** [applitools/eyes.sdk.javascript1#314]
It doesn't seem to be possible to test focused styles using eyes-storybook.

Is this a known issue?

#### Expected Result
![image](https://user-images.githubusercontent.com/18619846/101095909-b0a18100-358c-11eb-857f-a649dd274899.png)
#### Actual Result
![image](https://user-images.githubusercontent.com/18619846/101095950-c2832400-358c-11eb-8d05-ffc0d91c7f18.png)

#### style.css
```css
input {
  background-color: red;
  border: 2px solid orange;
}

input:focus {
  background-color: green;
  border-color: purple;
}
```
#### Focus.stories.js
```javascript
import React, { useState } from 'react';
import './style.css';

export default {
  title: 'Focus Test'
};

function Focus() {
  const [ hasFocus, setHasFocus ] = useState(false);

  return (
    <>
      <input
        onFocus={ () => setHasFocus(true) }
        onBlur={ () => setHasFocus(false) }
        autoFocus
      /><br />
      hasFocus: { JSON.stringify(hasFocus) }
    </>
  );
}

export const FocusTest = () => <Focus />;


export const FocusTest = () => <Focus />;
```
